[tool.poetry]
name = "femtow"
version = "0.1.1"
description = ""
authors = ["bruk.habtu <bruk.habtu@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
Routes = "^2.4"
backlash = "^0.1.4."
mako = "^1.0"
venusian = "^1.1"
webob= "^1.8"

[tool.poetry.dev-dependencies]
pytest = "^4.6"
black = "^19.10b0"
pre-commit = "^2.2.0"
gunicorn = "^20.0.4"
invoke = "^1.4.1"


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
