[tool.poetry]
name = "pyazo_cli"
version = "0.1.0"
description = ""
authors = ["Jelena Dokic <jelena.dpk@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.23.0"
pyperclip = "^1.8.0"
click = "^7.1.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
