[tool.poetry]
name = "djaxei"
version = "0.6.1"
description = "A django admin extension for importing exporting records from/to xls/ods"
authors = ["Giovanni Bronzini <g.bronzini@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/GigiusB/djaxei.git"
keywords = ["xls",]
include = ["README.md", "HISTORY.md", "Makefile"]
packages = [
    { include = "djaxei", from = "src" },
]

[tool.poetry.dependencies]
python = ">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*"
django = ">=1.11,<4"
openpyxl = { version = "<3", optional = true, extras = ["openpyxl"] }
xlwt = {version = "^1.2.0", optional = true, extras = ["xlwt"]}
xlsxwriter = {version = "^1.2.8", optional = true, extras = ["xlsxwriter"]}

[tool.poetry.dev-dependencies]
pytest = "<=5.0"
tox = "^3.14.6"
pytest-django = "^3.9.0"
django-webtest = "^1.9.7"

#pre-commit = "^2.1.1"
pytest-pythonpath = "^0.7.3"
flake8 = "^3.7.9"
isort = "^4.3.21"
factory_boy = "^2.12.0"
mock = "<3"


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
