[tool.poetry]
name = "nenucal"
version = "0.1.0"
description = "Calibration pipeline for the NenuFAR Cosmic Dawn project"
authors = ["\"Florent Mertens\" <\"florent.mertens@gmail.com\">"]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.6"
python-casacore = "^3.2.0"
#lsmtool = {git = "git+ssh://git@github.com:darafferty/LSMTool.git"}
#losoto = {git = "https://github.com/revoltek/losoto"}
asyncssh = "^2.1"
progressbar2 = "^3.0"
toml = "^0.10.0"
astropy = "^4.0"
matplotlib = "^3.0"
tables = "^3.2"
click = "^7.0"
scipy = "^1.4"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-cov = "^2.8.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
calpipe = "nenucal.tools.calpipe:main"
flagtool = "nenucal.tools.flagtool:main"
soltool = "nenucal.tools.soltool:main"
